/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OptionsImport } from './routes/options'
import { Route as HowToPlayImport } from './routes/how-to-play'
import { Route as GameOverImport } from './routes/game-over'
import { Route as GameImport } from './routes/game'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OptionsRoute = OptionsImport.update({
  path: '/options',
  getParentRoute: () => rootRoute,
} as any)

const HowToPlayRoute = HowToPlayImport.update({
  path: '/how-to-play',
  getParentRoute: () => rootRoute,
} as any)

const GameOverRoute = GameOverImport.update({
  path: '/game-over',
  getParentRoute: () => rootRoute,
} as any)

const GameRoute = GameImport.update({
  path: '/game',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameImport
      parentRoute: typeof rootRoute
    }
    '/game-over': {
      id: '/game-over'
      path: '/game-over'
      fullPath: '/game-over'
      preLoaderRoute: typeof GameOverImport
      parentRoute: typeof rootRoute
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayImport
      parentRoute: typeof rootRoute
    }
    '/options': {
      id: '/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof OptionsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  GameRoute,
  GameOverRoute,
  HowToPlayRoute,
  OptionsRoute,
})

/* prettier-ignore-end */
